runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /style
  static_dir: style

- url: /.*
  script: main.app


  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest
  
skip_files:
- lib/PIL/
- lib/Pillow-5.3.0.dist-info/
- PIL/